### ISSUE TITLE
Error: EEXIST: file already exists, symlink...

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli-htmlbars#104]
Environment: node 6.5.0, ember-cli 2.10.0, ember-cli-htmlbars 1.1.1

When I run `ember build`, I get

```
Build failed.
The Broccoli Plugin: [TemplateCompiler] failed with:
Error: EEXIST: file already exists, symlink '/Users/jamesarosen/Code/style-guide/node_modules/ember-freestyle/app/templates/components/freestyle-palette-item.js' -> '/Users/jamesarosen/Code/style-guide/tmp/template_compiler-output_path-PCqYFUPh.tmp/dummy/templates/components/freestyle-palette-item.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at FSMonitor._measure (/Users/jamesarosen/Code/style-guide/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.symlinkSync (/Users/jamesarosen/Code/style-guide/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at symlink (/Users/jamesarosen/Code/style-guide/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/Users/jamesarosen/Code/style-guide/node_modules/symlink-or-copy/index.js:55:5)
    at TemplateCompiler.Filter._handleFile (/Users/jamesarosen/Code/style-guide/node_modules/broccoli-persistent-filter/index.js:169:12)
    at TemplateCompiler.<anonymous> (/Users/jamesarosen/Code/style-guide/node_modules/broccoli-persistent-filter/index.js:146:23)
    at /Users/jamesarosen/Code/style-guide/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/jamesarosen/Code/style-guide/node_modules/rsvp/dist/rsvp.js:538:12)

The broccoli plugin was instantiated at:
    at TemplateCompiler.Plugin (/Users/jamesarosen/Code/style-guide/node_modules/broccoli-plugin/index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (/Users/jamesarosen/Code/style-guide/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new TemplateCompiler (/Users/jamesarosen/Code/style-guide/node_modules/ember-cli-htmlbars/index.js:20:10)
    at TemplateCompiler (/Users/jamesarosen/Code/style-guide/node_modules/ember-cli-htmlbars/index.js:12:12)
    at Object.toTree (/Users/jamesarosen/Code/style-guide/node_modules/ember-cli-htmlbars/ember-addon-main.js:32:34)
    at /Users/jamesarosen/Code/style-guide/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/jamesarosen/Code/style-guide/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessTemplates (/Users/jamesarosen/Code/style-guide/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)
    at EmberAddon.EmberApp._processedTemplatesTree (/Users/jamesarosen/Code/style-guide/node_modules/ember-cli/lib/broccoli/ember-app.js:836:48)
```

`freestyle-palette-item` is provided by [ember-freestyle](https://github.com/chrislopresto/ember-freestyle), but I override that template in my addon's `tests/dummy/app/templates/components/freestyle-palette-item.hbs`. The original and my override both use `.hbs`, so I don't think the problem is having two different compilers conflicting on an output. (See ember-cli/ember-cli#3413)

**Comment by jamesarosen** [comment]
I changed the `TemplateCompiler` constructor to do

```js
var log = require('broccoli-stew').log;
inputTree = log(inputTree, { output: 'tree', label: 'input to TemplateCompiler' });
Filter.call(this, inputTree, options); // this._super()
```

That yields

```
└── modules/
   └── modules/ember-freestyle/
      └── modules/ember-freestyle/templates/
         └── modules/ember-freestyle/templates/components/
            ├── modules/ember-freestyle/templates/components/freestyle-annotation.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-collection.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-guide.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-headers.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-menu.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-notes.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-palette-item.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-palette.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-section.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-snippet.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-subsection.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-typeface.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-usage-controls.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-usage.hbs
            ├── modules/ember-freestyle/templates/components/freestyle-variant-list.hbs
            └── modules/ember-freestyle/templates/components/freestyle-variant.hbs
⠧ Buildinginput to TemplateCompiler

└── dummy/
   └── dummy/templates/
      └── dummy/templates/components/
         ├── dummy/templates/components/.gitkeep
         ├── dummy/templates/components/freestyle-collection.js
         ├── dummy/templates/components/freestyle-guide.js
         ├── dummy/templates/components/freestyle-headers.js
         ├── dummy/templates/components/freestyle-menu.js
         ├── dummy/templates/components/freestyle-notes.js
         ├── dummy/templates/components/freestyle-palette-item.hbs
         ├── dummy/templates/components/freestyle-palette-item.js
         ├── dummy/templates/components/freestyle-palette.js
         ├── dummy/templates/components/freestyle-section.js
         ├── dummy/templates/components/freestyle-snippet.js
         ├── dummy/templates/components/freestyle-subsection.js
         ├── dummy/templates/components/freestyle-usage-controls.js
         ├── dummy/templates/components/freestyle-usage.js
         ├── dummy/templates/components/freestyle-variant-list.js
         ├── dummy/templates/components/freestyle-variant.js
         ├── dummy/templates/components/md-text.hbs
      └── dummy/templates/freestyle.hbs
```

Notice that both `dummy/templates/components/freestyle-palette-item.hbs` (from my own dummy app) and `dummy/templates/components/freestyle-palette-item.js` (already compiled from the addon's `app/` directory) are in the tree at that point.

**Comment by nathanhammond** [comment]
Duplicate/related to https://github.com/ember-cli/ember-cli/issues/5336

**Comment by jamesarosen** [comment]
> The original and my override both use .hbs, so I don't think the problem is having two different compilers conflicting on an output. 

This is wrong. ember-freestyle has an [hbs version in `addon/`](https://github.com/chrislopresto/ember-freestyle/blob/master/addon/templates/components/freestyle-palette-item.hbs), but then imports and reexports that as a [js version in `app/`](https://github.com/chrislopresto/ember-freestyle/blob/master/app/templates/components/freestyle-palette-item.js)

**Comment by jamesarosen** [comment]
@nathanhammond: you beat me by two seconds! 👏
