### ISSUE TITLE
Cannot find module 'fs-copy-file-sync' on Octane

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli-htmlbars#289]
Hi!

Our app is aligned with the latest Octane blueprint.

It seems to install `ember-cli-htmlbars` from @rwjblue's `colocation` branch. 

Our CI builds are crashing with this:

```
  - stack: Error: Cannot find module 'fs-copy-file-sync'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/ember-cli-htmlbars/lib/colocated-broccoli-plugin.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

This issue cannot be reliably reproduced on developer machines.

[Network](https://github.com/ember-cli/ember-cli-htmlbars/network) shows the `colocation-refactor` branch to be more recent, but I dunno if it's stable.

**Comment by rwjblue** [comment]
This should be resolved (please update to the latest SHA from the colocation branch to confirm), we had a missing dependency (it was in dev dependencies 🤦‍♂ ).
