### ISSUE TITLE
Import from `htmlbars-inline-precompile` is broken with v4.0.2

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-htmlbars#312]
It looks like v4.0.2 might disable `ember-cli-htmlbars-inline-precompile`, but does not support importing from `htmlbars-inline-precompile` anymore.

> Error: Could not find module `htmlbars-inline-precompile` imported from `skylines/tests/integration/components/flight-list-nav-test`

see: https://github.com/skylines-project/skylines/pull/1689

Was that an intended change?

/cc @rwjblue

**Comment by rwjblue** [comment]
Definitely not intended. Both old and new paths are intended to work (without deprecation even for a while).

**Comment by rwjblue** [comment]
Will work on it this morning, sorry folks 😕

**Comment by buschtoens** [comment]
Relatedly, presumably https://github.com/ember-cli/ember-cli-htmlbars/pull/286 is causing the following error:

```
[2019-10-01T10:51:52.009Z]   - broccoliBuilderErrorStack: Error: Duplicate plugin/preset detected.
[2019-10-01T10:51:52.009Z] If you'd like to use two separate instances of a plugin,
[2019-10-01T10:51:52.009Z] they need separate names, e.g.
[2019-10-01T10:51:52.009Z] 
[2019-10-01T10:51:52.009Z]   plugins: [
[2019-10-01T10:51:52.009Z]     ['some-plugin', {}],
[2019-10-01T10:51:52.009Z]     ['some-plugin', {}, 'some unique name'],
[2019-10-01T10:51:52.009Z]   ]
[2019-10-01T10:51:52.009Z]     at assertNoDuplicates (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
[2019-10-01T10:51:52.009Z]     at createDescriptors (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
[2019-10-01T10:51:52.009Z]     at createPluginDescriptors (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
[2019-10-01T10:51:52.009Z]     at alias (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
[2019-10-01T10:51:52.009Z]     at cachedFunction (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/caching.js:33:19)
[2019-10-01T10:51:52.009Z]     at plugins.plugins (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
[2019-10-01T10:51:52.010Z]     at mergeChainOpts (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-chain.js:319:26)
[2019-10-01T10:51:52.010Z]     at /home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-chain.js:283:7
[2019-10-01T10:51:52.010Z]     at buildRootChain (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/config-chain.js:68:29)
[2019-10-01T10:51:52.010Z]     at loadPrivatePartialConfig (/home/jenkins/agent/workspace/application_frontend_PR-8426/node_modules/@babel/core/lib/config/partial.js:85:55)
```

I guess this is because both, `ember-cli-htmlbars` and `ember-cli-htmlbars-inline-precombile`, register the same plugin.

**Comment by buschtoens** [comment]
I just saw that this was also reported as https://github.com/ember-cli/ember-cli-htmlbars/issues/297. Please excuse, if I am mixing up two distinct issues.
