### ISSUE TITLE
AST transforms no longer register in tests

### ISSUE THREAD

**Issue by offirgolan** [ember-cli/ember-cli-htmlbars#82]
```js
// index.js
setupPreprocessorRegistry: function(type, registry) {
    var VGet = require('./htmlbars-plugins/v-get');
    registry.add('htmlbars-ast-plugin', {
      name: "v-get",
      plugin: VGet
    });
}
```

```js
// tests/integration/helpers/v-get-test.js
moduleForComponent('helper:v-get', 'Integration | Helper | v-get', {
  integration: true
});
```

```
not ok 47 Chrome 52.0 - Integration | Helper | v-get: it renders
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: A helper named 'v-get' could not be found
                at new Error (native)
                at Error.EmberError (http://localhost:7357/assets/vendor.js:22077:21)
                at Object.Ember.default.assert (http://localhost:7357/assets/vendor.js:15178:13)
                at inline (http://localhost:7357/assets/vendor.js:17368:11)
                at Object.render (http://localhost:7357/assets/tests.js:386:11)
                at renderHTMLBarsTemplate (http://localhost:7357/assets/vendor.js:17861:21)
                at renderView (http://localhost:7357/assets/vendor.js:17828:16)
                at renderView (http://localhost:7357/assets/vendor.js:46828:5)
                at Class.render (http://localhost:7357/assets/vendor.js:46849:7)
                at EmberRenderer_createElement [as createElement] (http://localhost:7357/assets/vendor.js:48973:14)
        message: >
            Died on test #1     at testWrapper (http://localhost:7357/assets/test-support.js:12261:11)
                at test (http://localhost:7357/assets/test-support.js:12274:39)
                at Module.callback (http://localhost:7357/assets/tests.js:341:24)
                at Module.exports (http://localhost:7357/assets/vendor.js:131:32)
                at requireModule (http://localhost:7357/assets/vendor.js:30:18)
                at s (http://localhost:7357/assets/vendor.js:76651:143)
                at s (http://localhost:7357/assets/vendor.js:76651:123): Assertion Failed: A helper named 'v-get' could not be found
        Log: |
```

@rwjblue has noted that this may be related to: 

- ember-cli/ember-cli-htmlbars#81
- ember-cli/ember-cli-htmlbars-inline-precompile#30

PR: offirgolan/ember-cp-validations#279
Build: https://travis-ci.org/offirgolan/ember-cp-validations/jobs/148121235

**Comment by rwjblue** [comment]
Basically, we need to just move the following lines from ember-cli-htmlbars-inline-precompile into ember-cli-htmlbars itself:

* https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L5
* https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L13-L15
* https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L34
* https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L40-L45

**Comment by rwjblue** [comment]
Just wanted to capture some conversation here, hopefully someone can pick this up fairly quickly from these breadcrumbs.  I sadly won't be able to get to it until the weekend.

![screenshot of slack conversation](https://monosnap.com/file/yqCKiVO6W69dg6ey7tvIlk1X8AeW0Q.png)

**Comment by offirgolan** [comment]
@rwjblue any updates on this?

**Comment by rwjblue** [comment]
Sorry for the delay. I've been working on https://github.com/babel/broccoli-babel-transpiler/pull/89 which is related. Once that lands (hoping today/tomorrow) we can land your open PR's to migrate the inline compiling functionality into this repo.

**Comment by offirgolan** [comment]
Fantastic! Thank you 😺
